🔨 rodando o projeto local durante o test e2e

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -23,6 +23,22 @@ jobs:
     - name: Build and run Docker Compose
       run: docker-compose up -d --build
 
+    - name: Wait for the application to be ready
+      run: |
+        echo "Waiting for the application to start..."
+        ATTEMPTS=0
+        MAX_ATTEMPTS=30
+        until $(curl --output /dev/null --silent --head --fail http://localhost:3000) || [ $ATTEMPTS -eq $MAX_ATTEMPTS ]; do
+          printf '.'
+          ATTEMPTS=$((ATTEMPTS+1))
+          sleep 10
+        done
+        if [ $ATTEMPTS -eq $MAX_ATTEMPTS ]; then
+          echo "Application failed to start within expected time."
+          exit 1
+        fi
+      timeout-minutes: 5
+
     - name: Install dependencies
       run: npm ci
 
